name: Build Check

on:
  pull_request:
    branches: [main, test]
  push:
    branches: [main, test]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run build
        run: npm run build
      
      - name: Check build artifacts
        run: |
          if [ ! -d "dist" ] && [ ! -d "build" ] && [ ! -d "_site" ]; then
            echo "Warning: No common build output directory found"
          fi
      
      - name: Run tests (if available)
        run: |
          if npm run | grep -q "test"; then
            npm run test
          else
            echo "No test script found, skipping tests"
          fi
      
      - name: Run linting (if available)
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          else
            echo "No lint script found, skipping linting"
          fi